In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)
   
   
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - $2\times 3$; $BA$ - неопределена
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $8\times 8$;  $BA$ - $3\times 3$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

In [10]:
A = np.array([[1, 1], [2, 2], [3, 3], [4, 4]])
B = np.array([[1, 1], [2, 2], [3, 3], [4, 4]])
print('a) Недопустимая операция')
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

a) Недопустимая операция
Матрица A
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
Матрица B
[[1 1]
 [2 2]
 [3 3]
 [4 4]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [11]:
A = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
B = np.array([[1, 2, 3], [3, 2, 1], [4, 5, 6], [6, 5, 4], [7, 8, 9]])
print('б) АВ - допустима, ВА - недопустимая операция')
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}') 

б) АВ - допустима, ВА - недопустимая операция
Матрица A
[[1 2 3 4 5]
 [1 2 3 4 5]]
Матрица B
[[1 2 3]
 [3 2 1]
 [4 5 6]
 [6 5 4]
 [7 8 9]]
Матрица AB
[[78 81 84]
 [78 81 84]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 7], [6, 5, 4], [3, 2, 1], [1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8]])
print('в)')
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

в)
Матрица A
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]
 [1 2 3]
 [4 5 6]]
Матрица B
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
Матрица AB
[[  6  12  18  24  30  36  42  48]
 [ 15  30  45  60  75  90 105 120]
 [ 24  48  72  96 120 144 168 192]
 [ 24  48  72  96 120 144 168 192]
 [ 15  30  45  60  75  90 105 120]
 [  6  12  18  24  30  36  42  48]
 [  6  12  18  24  30  36  42  48]
 [ 15  30  45  60  75  90 105 120]]
Матрица BA
[[153 159 165]
 [153 159 165]
 [153 159 165]]


In [13]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 6], [5, 4, 3, 2]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 6], [5, 4, 3, 2]])
print('г)')
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

г)
Матрица A
[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]
Матрица B
[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]
Матрица AB
[[ 58  54  50  46]
 [138 134 130 126]
 [142 146 150 154]
 [ 62  66  70  74]]
Матрица BA
[[ 58  54  50  46]
 [138 134 130 126]
 [142 146 150 154]
 [ 62  66  70  74]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ 

In [14]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма матриц A + B\n{A + B}')
print(f'Произведение AB\n{np.dot(A, B)}')

Сумма матриц A + B
[[ 5 -3]
 [ 3  5]]
Произведение AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [15]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

B2 = -2*B

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = \n{3*A + B2 + 4*C}\n") 

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = 
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [16]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
print(f'Матрица AA^T\n{np.dot(A, AT)}')
print(f'Матрица A^T*A\n{np.dot(AT, A)}')

Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^T*A
[[45  0]
 [ 0 14]]


__5.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

  б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [17]:
A = np.array([[4, 1], [5, -2]])
print('а)')
print(f'Определитель:\n sin^2(x)+cos^2(x) = 1')

а)
Определитель:
 sin^2(x)+cos^2(x) = 1


In [18]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print('б)')
print(f'Определитель:\n 4 * 5 * 9 = 180')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

б)
Определитель:
 4 * 5 * 9 = 180
Определитель:
180


In [19]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('в)')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

в)
Определитель:
-0


__6.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [21]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель:\n{np.linalg.det(A):.0f}')
print('Матрица вырожденная, потому что определитель равен 0 ')

Определитель:
0
Матрица вырожденная, потому что определитель равен 0 


__7.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [22]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 2
